ballsdex/packages/admin/cog.py

Right now it takes an int but doesnt detect server IDs as an actual integer.
Now it takes a str and casts it to an int while searching.

Fix admin cooldown not accepting guild ids

---

ballsdex/__main__.py
ballsdex/settings.py
config.json.example
docker-compose.yml

This PR implements the required pieces to get the gateway proxy working on this bot.
It requires a config.json file for the gateway proxy container, a example is included.
Then for the bot to be able to connect using the gateway proxy sessions, the `gateway_url` field must be provided in the config.yml file. In this context it will simply be `gateway_proxy:5421`.
Closes #56.

Implement gateway proxy support

---

ballsdex/core/admin/resources.py
ballsdex/core/bot.py
ballsdex/core/commands.py
ballsdex/core/models.py
ballsdex/packages/players/countryballs_paginator.py
migrations/models/17_20230415141405_update.sql

Adds emoji support for special events which will show in trades etc
NOTE: Due to a discord limitation, you cannot show custom emojis in autocomplete/selection models.
Another limitation, the database just stores raw text like `:egg:`, to support showing unicode emojis in those model fields we will need to change handling to convert emoji to its unicode equivalent which is not part of this PR. Instead a generic lightning emoji is used to signify a special card.

feat: Add emoji support for special cards

---

ballsdex/core/bot.py
ballsdex/packages/players/cog.py
ballsdex/packages/trade/cog.py
ballsdex/packages/trade/menu.py

This PR achieves the first suggestion brought up in core chat. It will keep track of all balls in an active trade or donation.
Suggestion 2 to limit trades to 1 globally would have to be another PR

Fix ability to give away balls in an active trade

---

ballsdex/core/bot.py
ballsdex/packages/players/cog.py

Removes the User argument on balls list, replaces with Member and adds a transformer error to bot on error to handle stuff that cannot be converted.

Remove ability to user lookup on list

---

ballsdex/packages/trade/menu.py

Fix a bug where balls are not unlocked from both clearing and cancelling a trade.
Resolves #214.

[Trade] Unlock balls on clear.

---

ballsdex/core/models.py

I believe this is the root of the extra space, not the actual command in balls cog.

Fix extra space in /ball give

---

ballsdex/packages/trade/cog.py

Since that already exists in /trade add, why not add it to /trade remove as well. Small addition that would help with bulk trades.

add special and shiny arg to /trade remove

---

ballsdex/packages/admin/cog.py

making the response "Guild isn't blacklisted" in blacklist info guild ephemeral, also some description fixes for them to make sense.

response changed to ephemeral msg in admin cog + some arg description fixes

---

ballsdex/packages/admin/cog.py

this of course is so that in other dexes, the "countryball" will get translated as {settings.collectible_name}.

in many descriptions, changing "ball" to "countryball"

---

ballsdex/core/bot.py

I imported `time` because `datetime` is much more limiting, and kind of useless. Works with Discord, verified it.

[core] For cooldown show active timer

---

CONTRIBUTING.md

small changes but makes it look more formal

adding punctuation (full stops) in CONTRIBUTING.md

---

ballsdex/core/bot.py

handling permission checks correctly with details

---

ballsdex/core/admin/resources.py
ballsdex/core/models.py
ballsdex/packages/config/cog.py
ballsdex/packages/config/components.py
ballsdex/packages/countryballs/components.py
migrations/models/32_20240830012954_update.sql

every response from guessing messages except catch message and spawn is ephemeral.
closes #68

[config] /config silent, prevents notification spam

---

ballsdex/packages/admin/cog.py

just so that translation to settings.collectible_name works

[admin] changing ball to countryball in command arg names

---

ballsdex/packages/config/cog.py

Adds a missing space from if you disable spawning via /config disable, as it would previously display as this:
```
BallsDex is now disabled in this server. Commands will still be available, but the spawn of new countryballsis suspended.
To re-enable the spawn, use the same command.
```
however it now displays this:
```
BallsDex is now disabled in this server. Commands will still be available, but the spawn of new countryballs is suspended.
To re-enable the spawn, use the same command.
```
(credits to @seifdafisherman on Discord/GitHub for finding this, just thought i'd try to make a quick patch for it)
https://canary.discord.com/channels/1049118743101452329/1284830182691180696

Add missing space from /config disable

---

README.md

This is a bit of a stupid pull request, but my inner ocd really wants the badges to match with each other, so I’ve replaced the stock Discord API badge displaying the online counter, with one from shields.io that matches the rest of the badges more similarly, and with a modernised logo and look overall.

Modernize Discord server badge

---

ballsdex/core/admin/resources.py
poetry.lock
pyproject.toml

Fixes #455 
Fork `fastapi-admin` to remove pendulum dependency. This is needed as pendulum wheels are missing for 3.13 (see https://github.com/sdispater/pendulum/issues/844), triggering a rebuild which needs rust to compile. Adding rust to our docker image would make it considerably slower and heavier, thus removing the dependency is easier.
`fastapi-admin` uses pendulum for datetime filtering which we don't use. The poetry now points to our own fork. This fork may be used in the future to add some fixes that were not added to the original repo.

poetry: remove pendulum dependency

---

ballsdex/packages/players/cog.py

this prevents player1 from sending a friend request to player2 if player2 has an active friend request to player1

[player] Add check to prevent double friend requests

---

ballsdex/packages/admin/balls.py

Due to the latest admin panel changes, the static folder was switched to `admin_panel/media`, however, the `save_file` function in `ballsdex/packages/admin/balls.py` still uses the `/static/uploads` folder.

[admin] Fix file path in `save_file`

---

ballsdex/packages/balls/cog.py

If a user has request approval on, then the followup message confirming it references the ephemeral message - thus making it hard to see where it comes from

[trade] change donation message if having to request approval

---

ballsdex/core/image_generator/image_gen.py

This is a pretty small change that moves the ability description up one line in the event that the ability name is one line long. 
Example below; details of card hidden because it contains PII and whatnot. The only relevant part is the spacing between the ability name and description, which on the previous fork would be padded an extra 100px.
Yes, tested on my fork (along with other changes) and with dummy data on this branch

Move capacity description based on length of title

---

.dockerignore
Dockerfile
docker-compose.yml

This PR adjusts the setup of the dockerfile & docker compose to do the following
- Rebase on Alpine instead of on Debian—it's lighter and builds faster
- Disable pycache; it's not needed in docker and clutters the directories
- Move the initial poetry install to before the code is copied. Because Docker caches builds, this ensures that the build will only re-install dependencies if the poetry file changes; this should make the vast majority of builds significantly faster since we no longer install a heap of dependencies
- Remove poetry cache after build so it isn't included in the final image.
- Remove the 2s delay for postgres (see docker-compose.yml changes)
- This PR adds a dockerignore containing files that shouldn't be embedded in the image
- For example, before this, any change to …

Change setup of Docker

---

ballsdex/settings.py

Removes the default ballsdex url and tos/privacy policy.
closes #574

[settings] remove default invite & privacy/tos urls.

---

ballsdex/core/models.py
ballsdex/packages/admin/cog.py
ballsdex/packages/admin/money.py
ballsdex/packages/players/cog.py

Adds admin commands to view, set, add and remove coins.
Adds player money give and balance
Yes

[currency] add commands to admin and player cog for currency

---

ballsdex/packages/balls/cog.py
ballsdex/packages/balls/countryballs_paginator.py

Adds an optional limit arg, if the value is 0 or more than the amount of balls that the user owns it shows all, the limit is ignored on all specials. It also extends the limit from 50 to all, and also adds a plural check when a user clicks on a ball in the menu.
Yes, but with 3 balls and 2 specials only, not more.

[balls duplicate] Add limit arg, extend the limit from 50, plural check

---

ballsdex/__main__.py
ballsdex/packages/countryballs/countryball.py
ballsdex/settings.py

This PR allows users to configure spawn, catch, slow, and wrong messages within the config.yml
I didn't make it configurable from the DB because a) I don't think people are changing this that much b) db calls are slow (comparatively) and there are a lot of messages sent and lastly and most importantly c) I don't want to deal with DB nonsense
Users change format strings in the config.yml, and the bot picks a random one, formats it, and sends it instead of the prior hardcoded strings. It provides the ball name, the collectible singular and plural, and a mention for the user. I did not weight the messages, because I don't think I would use that and can't really think of a usecase.
I think I did all the yml things right, but I'm not sure, because that thing is a terrifying agglomeration of …

Configurable spawn messages

---

ballsdex/packages/balls/cog.py

Allows to filter completion by collectibles that are self caught (ie not received from a trade) or not self caught (ie only received from trade / give)
I used trade_player_id because I think that avoids a SQL join? Not sure it might also be a foreign key. Also, using __isnull because I want to be able to filter for both true and false.
I didn't use FilteringChoices because I would have to refactor this whole function I think, and I'm not sure how I would make it work.
Yes

Add filtering by self-caught in completion

---

.dockerignore
Dockerfile

Builds are currently broken because libraqm is in edge community now, not edge testing. So this PR switches to that repo. 
Yes

Update libraqm repo

---

ballsdex/__main__.py

Fixes this typo
Yes
(just strings)

Fix missing space in config error message

---

admin_panel/bd_models/migrations/0004_check_aerich_migrations_initial.py

As per [conversation on discord](https://discord.com/channels/1255250024741212262/1255255977029144596/1395801542078103712) because the  migrations imported from models, trying to add a new column in models would error in 004_check_aerich_migrations because it would try to insert data for a column that would not exist at the time. This fixes that issue so it's again possible to add columns to specials, economies, and regimes.
Also changes formatting on a couple lines because pre-commit was complaining.
Yes, also tested to make sure I could add new columns and I could.
Should probably test on a DB with content in it already but I didn't have one on hand.

Instead of importing explicitly in migration, grab models from app registry
