ballsdex/core/utils/buttons.py, ballsdex/packages/trade/cog.py
Due to community suggestions, adding a confirmation button to trade when ball is favourited.
First time actually trying to use views, let me know if there's anything wrong.
=> FEAT: Add confirmation check to trading favourite ball.

ballsdex/core/admin/resources.py
Adds searching on ID, ball ID and player ID to the ball instance panel.
=> feat: add searching to ball instance panel

ballsdex/packages/info/cog.py
Right now there's a chance it'll pick disabled balls and show their emojis, which apparently confuses people
=> BUG: Only show enabled balls in about list

ballsdex/__main__.py, ballsdex/core/bot.py, ballsdex/settings.py
Add an optional config parameter to pass a list of IDs to be considered coowners.
Still to test, marking as draft.
closes #60
=> FEAT: Add support for multiple owners

ballsdex/packages/countryballs/components.py
=> FEAT: Include text when the ball caught is your first.

ballsdex/packages/admin/cog.py
New commands that adds the following:
- Ball lookup
- Ball transfer
- Ball delete
- Account reset
- Count of how many
Note: Not tested, not at pc with a ballsdex setup atm
Closes #83
=> [Admin] New admin commands

ballsdex/packages/players/cog.py
Adds user argument to /balls last
=> Add user arg to balls last

ballsdex/packages/players/cog.py
add option to sort by:
health bonus
attack bonus
stats (hp and attack)
and added a reverse option
=> Add stats, health and atk listing to balls list

ballsdex/packages/admin/cog.py
Changes more admin commands that return info to use ephemeral responses.
=> [Admin] Move more commands to ephemeral

ballsdex/core/bot.py
Should be ahead of invoke, it isnt being handled in current location
=> Fix location of error handling

ballsdex/core/models.py, ballsdex/packages/admin/cog.py, ballsdex/packages/countryballs/components.py, migrations/models/21_20231113175415_update.sql
TODO: Generate migrate file once local is back up and running
=> Add spawn info to ballinstance

ballsdex/packages/countryballs/countryball.py
countryballs: check for correct permission before sending
=> countryballs: check for correct permission before sending

ballsdex/packages/admin/cog.py, ballsdex/packages/players/cog.py
Added shiny dictionary for the prompt message, added it in the f string, and also added if balls = 0 for the plural, since it should be "0 countryballs" rather than "0 countryball". First time creating a PR, so hope this works haha, cheers.
=> Fixed shiny case for balls count

ballsdex/core/admin/resources.py, ballsdex/core/models.py, ballsdex/packages/players/cog.py, migrations/models/25_20240109160009_update.sql
Add the ability to view your completion of special events or shinies.
=> Add special & shiny to completion command

ballsdex/packages/trade/cog.py
Add ability to view your trades with a specific user
=> [Trade] Add optional user arg to trade history

ballsdex/packages/trade/cog.py
Add a cancel trade command incase the interactions fail.
=> [trade] add trade cancel

ballsdex/packages/countryballs/components.py
=> Add atk and hp stat and stat bonus to spawn message

ballsdex/packages/config/components.py
really small but big issue lol
=> Config tos and policy fix!

ballsdex/packages/players/cog.py
=> Replace balls give with settings.players_group_cog_name give

ballsdex/packages/players/cog.py
Add a deletion and export command
Export allows you to specify collectible, trades or all
closes #235
=> [players] add delete and export command

ballsdex/packages/admin/cog.py
It is just some details, such as adding some brackets, full stops etc.
=> admin cog.py improvements (mostly typo fixes)

ballsdex/packages/config/cog.py, ballsdex/packages/config/components.py
they were pretty significant typos, as seeing "creating servers for countryball", and "countryball will start spawning" are pretty big grammar mistakes.
=> config typo fixes

ballsdex/packages/balls/cog.py, ballsdex/packages/trade/cog.py
minor fixes in trade cog and balls cog
=> change countryball to {settings.collectible_name} in a few places

ballsdex/packages/balls/cog.py
=> remove favourite by donation accept 

ballsdex/packages/trade/cog.py
=> [Trade] Add ball arg to trade history

ballsdex/packages/balls/cog.py
it pretty much made the special description all go to the countryball description, sry about that
=> small space fix

ballsdex/core/admin/resources.py
it was unused for a while not anymore!
=> Put hidden to use in panel

ballsdex/packages/admin/cog.py
Add log action to spawn bomb & make message ephemeral
=> [admin] add log action to spawn bomb

ballsdex/packages/balls/cog.py
=> [countryballs] add special arg to balls list

ballsdex/settings.py
related to issue in #293 this will not happen in the further!
=> Handle every text-prefix as a string

ballsdex/core/utils/buttons.py, ballsdex/packages/balls/cog.py
confirm favourite in balls give
When testing please double check the followup messages after, this has not been tested - unsure if the confirm check defers the entire interaction
=> [balls] confirm favourite in balls give

ballsdex/packages/balls/cog.py
it was missing from there, so why not add it, helps make everything faster for users with many countryballs.
=> adding `special` and `shiny` arg to `/balls favourite`

ballsdex/packages/admin/cog.py
when i was testing things with my self host, i made a new server, with no pfp, and when i ran the cmd admin info guild it failed, this fixes it!
=> slight issue fix with admin info guild

README.md
=> Update README to remove "we no longer maintain a support server" things

ballsdex/packages/admin/cog.py
this is in /admin history ball btw
=> changing "ball" to "countryball" so that it gets replaced with {settings.collectible_name}

ballsdex/packages/balls/cog.py
=> Add missing characters in the balls cog

ballsdex/packages/balls/cog.py
=> very small changes to wording in 2 occasions on balls give

ballsdex/packages/admin/cog.py
=> grammatical changes to admin info guild/user

ballsdex/packages/trade/cog.py
=> fixing trade history sort countryball

ballsdex/packages/balls/countryballs_paginator.py
maybe better syntax is needed to this
=> seeing stats through balls list

ballsdex/packages/trade/cog.py, ballsdex/packages/trade/display.py, ballsdex/packages/trade/menu.py
=> [trade] Add trade view

ballsdex/packages/balls/countryballs_paginator.py
removing the caught on, makes it look better
=> [balls] changing syntax for stats through balls list

ballsdex/core/commands.py
=> adding a . at a bot response

ballsdex/core/bot.py, ballsdex/packages/admin/__init__.py, ballsdex/packages/countryballs/cog.py
=> [ballsdex] grammar checks/small fixes in logged info

ballsdex/packages/players/cog.py
shows your current completion, the amount of countryballs, shiny countryballs and special countryballs you own, and the trades you have done. this can be updated if new features get added.
closes #356
=> [player] new /player stats command

ballsdex/core/utils/paginator.py
Removes the confusing entries text from embed footers
closes #98
=> [pagination] remove "entries" from footer

ballsdex/packages/players/cog.py
this allows for a lot more information to be showed in the embed
closes #420
=> [player] Change `/player stats` to `/player info`

ballsdex/packages/players/cog.py
=> [player] checking if there is an active friend request before sending another one

ballsdex/templates/base.html
If anyone has any design suggestions, or maybe adding the js/css in a seperate folder, or literally any feedback, I would love to hear it.
=> [admin panel] dark mode, and a toggle to switch from one mode to another

ballsdex/packages/countryballs/spawn.py
I had some problem reading the code and I realised it is because the variable names are kinda meaningless, so I changed them, without changing the behaviour.
multiplier? - there are 2 distinct multipliers
delta what? - delta_time
amount? Thats the most meaningless name for a number? chance? it is a `threshhold`, a randomly determined threshold to be exact
amount and self.amount in the same function also confused me for a second
=> beautify spawn.py

ballsdex/core/bot.py, ballsdex/settings.py
This change makes it easier for self-hosted owners to add custom packages (without having to modify the bot.py file).
=> [settings] move packages to settings

ballsdex/core/admin/resources.py, ballsdex/core/image_generator/image_gen.py, ballsdex/core/metrics.py, ballsdex/core/models.py, ballsdex/core/utils/transformers.py, ballsdex/packages/admin/balls.py, ballsdex/packages/balls/cog.py, ballsdex/packages/balls/countryballs_paginator.py, ballsdex/packages/countryballs/components.py, ballsdex/packages/countryballs/countryball.py, ballsdex/packages/players/cog.py, ballsdex/packages/trade/cog.py, ballsdex/packages/trade/menu.py, migrations/models/36_20241009120300_update.sql
This is taken from #436 but as a separate PR, since it's a change that would be very benefical in general, doesn't need to wait for the other stuff from that PR to be ready
=> models: remove shinies, replace by pre-made special

ballsdex/packages/balls/cog.py
=> [balls] Handle more DoesNotExist errors

ballsdex/core/bot.py, ballsdex/packages/info/cog.py
=> [info] Add uptime in the command /about

ballsdex/packages/admin/history.py
=> [admin] makes sorting arg optional, adds countryball arg to /admin history user

admin_panel/admin_panel/middleware.py, admin_panel/admin_panel/settings/production.example.py, admin_panel/admin_panel/settings/production_base.py
Frankly, in reality, these could also be applied on the Reverse proxy side, buutttt... This stops others from miss-configuring it.
=> Add in more server sided security options

.pre-commit-config.yaml, ballsdex/core/bot.py, ballsdex/core/commands.py, ballsdex/core/dev.py, poetry.lock, pyproject.toml
=> Update to discord.py 2.5.0

ballsdex/packages/players/cog.py
Added "amount of users traded with" to /player info, below trades completed field.
resolves #567
Yes
=> [player] Add "amount of users traded with" to /player info

ballsdex/core/utils/sorting.py
=> [sorting] Remove bonus from sorting

ballsdex/packages/balls/cog.py
Adds /balls compare to be able to compare your collection with another user.
Briefly with 4 balls, needs more testing with bigger collections and specials
=> [balls] Add balls compare

ballsdex/packages/trade/menu.py
=> [trade] Check locked status after confirming

ballsdex/packages/balls/cog.py, ballsdex/packages/balls/countryballs_paginator.py
Changes balls duplicate to use select menu instead of an embed
The countryball type was tested, specials was not
=> [balls] change duplicate into select menu

ballsdex/__main__.py, ballsdex/core/bot.py
Changes "disable_messsage_content" to "disable_message_content".
Yes
=> Fix a little typo in bot.py.

admin_panel/admin_panel/admin.py
Use settings.bot_name instead of "BallsDex"
Yes
=> [admin panel] Use configured bot name instead of "BallsDex"

ballsdex/core/utils/sorting.py, ballsdex/packages/balls/cog.py, ballsdex/packages/trade/cog.py
Adds a filter arg to balls list and bulk add - ability to filter to only specials, non specials, self caught and balls caught in this server
Yes
=> [filtering] Add filtering arg to balls list and bulk add

ballsdex/packages/balls/cog.py
Addition of /balls collection for a publicly viewable insight into your total or specific ball collection
Yes
=> Add balls collection

ballsdex/packages/admin/history.py
Add get_or_none instead of get to db call
Yes
No
=> [admin] Fix an error with ball ID in admin history

ballsdex/packages/balls/cog.py, ballsdex/packages/countryballs/spawn.py
Added an optional choice to hide the collection command, if you don't want to show it to others - I personally would find this useful for checking what balls I have (instead of running count several times)
Yes. It has not been tested on a large database but the change is minor so that probably shouldn't matter
=> add ephemeral to collection

admin_panel/bd_models/admin/special.py, ballsdex/core/image_generator/image_gen.py
=> Change special credit loc and add to panel

ballsdex/packages/countryballs/countryball.py
Change `player` and `trade_player` to `player_id` and `trade_player_id`
Yes
=> [countryballs] Fix `if self.ballinstance` in `catch_ball`

ballsdex/core/bot.py
There's a small bug in "auto lower translations" change, it also applies that to everything (command descriptions, options, etc.). I made a fix for it, but not sure will it work.
No
=> Fix for auto lower translations bug

ballsdex/packages/balls/cog.py, ballsdex/packages/balls/countryballs_paginator.py, ballsdex/packages/trade/cog.py, ballsdex/packages/trade/menu.py
Use PK indexes instead of the objects for faster lookup.
=> [balls] improve search times in all balls commands

ballsdex/packages/admin/history.py, ballsdex/packages/balls/cog.py, ballsdex/packages/trade/display.py
=> Small text changes
